### PR TITLE
Server rewrite

### LINKED ISSUE #1: Server example doesn't work
I can't get the server example to work, can you provide a working example project?

### PR DESCRIPTION
**Pull request by GambolingPangolin**
The JSON RPC implementation was broken and this adds a working implementation.  The idea is to have a type `RawJsonRpc` which fits into a Servant API definition.  To implement the handler for this endpoint, first implement handlers for each JSON RPC method, then compose them using `:<|>` as usual and the new function `serveJsonRpc`.

Status: barely tested.

closes #1 

- [x] update project README 
- [x] test notifications and failures in examples branch

### CODE REVIEW

File: servant-jsonrpc-server/src/Servant/Server/JsonRpc.hs [hunk 1]
```diff
@@ -1,65 +1,163 @@
...
+        = h v >>= \case
+            SomeContent (Right x) | Just ix <- ix' -> return . SomeContent $ Result ix x
+                                  | otherwise      -> return . SomeContent $ Errors ix' invalidRequestErr
+            SomeContent (Left e)                   -> return . SomeContent $ Errors ix' e
+            EmptyContent                           -> return EmptyContent
+        | otherwise = return . SomeContent $ Errors ix' missingMethod
         where
-        f x (Request _ p _) = x p
-        endpoint = Proxy @(JsonRpcEndpoint (JsonRpcNotification method p))
+        missingMethod     = JsonRpcErr methodNotFound ("Unknown method: " <> m) Nothing
```
Comment (GambolingPangolin) [inline servant-jsonrpc-server/src/Servant/Server/JsonRpc.hs]: whitespace

File: servant-jsonrpc/servant-jsonrpc.cabal [hunk 2]
```diff
@@ -1,7 +1,7 @@
 cabal-version:       2.4
 
 name:                servant-jsonrpc
-version:             1.0.0
+version:             1.1.0
```
Comment (GambolingPangolin) [inline servant-jsonrpc/servant-jsonrpc.cabal]: This is a non-breaking change.  Bump version to `1.0.1`.

File: servant-jsonrpc/src/Servant/JsonRpc.hs [hunk 3]
```diff
@@ -22,14 +22,22 @@
...
+      RawJsonRpc
+    , JsonRpc
     , JsonRpcNotification
 
     -- * JSON-RPC messages
     , Request (..)
     , JsonRpcResponse (..)
     , JsonRpcErr (..)
 
+    -- ** Standard error codes
```
Comment (GambolingPangolin) [inline servant-jsonrpc/src/Servant/JsonRpc.hs:34]: Add the `Code` suffix to these or put them in a new module.
